### ISSUE TITLE
pages少了logs页面

### ISSUE THREAD

**Issue by yangqinjiang** [jayZOU/skeleton#1]
pages/logs/logs

**Comment by yangqinjiang** [comment]
实际应用中,还是发觉有一点不方便的地方,例如, 异步请求回的数据经过setData后, 视觉上有点差别.
难道要在data里预先填充数据吗?

**Comment by jayZOU** [comment]
骨架屏只是填充一个大概的轮廓，跟正式数据页面相比较有差异是正常，所以骨架屏大多数会应用在页面结构较为固定的页面。

小程序里面需要预填充数据才能撑起页面结构（有相应的width和height），这样才能渲染相应的骨架屏
