### ISSUE TITLE
用mpvue写小程序页面，进入页面会闪现原有界面，在回到骨架屏，最后回到原有页面。

### ISSUE THREAD

**Issue by ChanXK** [jayZOU/skeleton#10]

**Comment by ChanXK** [comment]
头疼，有大佬遇到这个问题，知道怎么解决吗

**Comment by jayZOU** [comment]
给下示例代码，从描述上来看是因为打开页面的时候并没有隐藏掉原有页面

**Comment by ChanXK** [comment]
<skeleton selector="skeleton" bgcolor="#FFF" v-if="showSkeleton"></skeleton>
    <div class="skeleton ">
      <div class="user ">
        
        <div class="head skeleton-radius ">
          <img :src="userInfo.avatar" class="head-img" alt />
        </div>
        <div class="userinfo ">
          <div>
            <p class="name skeleton-rect rect" >{{userInfo.name}}</p>
            <p class="commonper skeleton-rect rect">普通会员</p>
          </div>
          <div class="price">
            <p class="rest skeleton-rect rect">
              余额：
              <span>{{userInfo.balance}}</span>
            </p>
            <p class="num-fen skeleton-rect rect">
              积分：

**Comment by ChanXK** [comment]
我用的mpvue写的，好像没有用大佬你的组件

**Comment by ChanXK** [comment]
不过可以指点下吗

**Comment by jayZOU** [comment]
`<skeleton selector="skeleton" bgcolor="#FFF" v-if="showSkeleton"></skeleton>
<div class="skeleton " v-else>`

加个v-else试试

**Comment by jayZOU** [comment]
<skeleton selector="skeleton" bgcolor="#FFF" v-if="showSkeleton"></skeleton>
<div class="skeleton " v-else>

加个v-else试试

**Comment by jayZOU** [comment]
```
<skeleton selector="skeleton" bgcolor="#FFF" v-if="showSkeleton"></skeleton>
<div class="skeleton " v-else>
...
</div>
```
加个v-else试试
