### ISSUE TITLE
自定义组件中使用的问题

### ISSUE THREAD

**Issue by yeslife-click** [jayZOU/skeleton#15]
发现有一种情况下似乎无法正常使用：假设cul是一个自定义组件，cli是一个自定义组件，当cul与cli存在组件间关系的时候，获取到cli组件的宽高和位置信息全部为0。大概看了一下，好像是由于当两个组件存在关系时，skeleton获取各个节点信息时，cli还没有初始化。这种情况有什么好的解决方法么？

https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/relations.html

**Comment by jayZOU** [comment]
@yeslife-click 给li默认的初始数据(data)来撑开宽高试试

**Comment by yeslife-click** [comment]
**试过了也不行，实际情况比之前描述的还要复杂一点，父组件与子组件存在组件间关系，大概是这么个样子。**
父组件：
```
<parent>
  ...
  <slot></slot>
</parent>
```
子组件：
```
<child>
  ...
  <slot></slot>
</child>
```
index.wxml：
```
<skeleton .....selector="skeleton"></skeleton>
<view class="skeleton">
<parent>
  <child>
    <text class="skeleton-rect">123</text>
  </child>
  <child>
    <text class="skeleton-rect">123</text>
  </child>
</parent>
</view>
```
**<skeleton>能获选择到text标签，但是在计算元素宽、高和位置信息时全部为0**

**Comment by jayZOU** [comment]
@yeslife-click 修复了，再试试
