### ISSUE TITLE
是否支持分块，项目中数据可能是多个请求，现在是直接关闭骨架屏。

### ISSUE THREAD

**Issue by 851091009** [jayZOU/skeleton#16]

**Comment by 851091009** [comment]
![1](https://user-images.githubusercontent.com/8460036/72119971-50f92080-3391-11ea-8d6c-cc2397b8bf30.gif)
这种效果支持吗？谢谢

**Comment by jayZOU** [comment]
@851091009 可以考虑支持下

**Comment by 851091009** [comment]
好的，非常感谢！
