### ISSUE TITLE
大佬，可以做成npm包，用起来可以更方便？

### ISSUE THREAD

**Issue by habc0807** [jayZOU/skeleton#19]

**Comment by habc0807** [comment]
我尝试封了下，能用

https://github.com/habc0807/miniprogram-skeleton-component

**Comment by jayZOU** [comment]
@habc0807 欢迎提MR

**Comment by habc0807** [comment]
很荣幸

**Comment by habc0807** [comment]
提PR了，大佬得空review下代码

**Comment by jayZOU** [comment]
@habc0807 
1、miniprogram_dev 可以删了吧，源码放src就好了
2、构建出来的 dist有冗余的文件，导致小程序包体积过大，不需要的文件配置下 npmignore
3、要么全部用ts，要么不用

**Comment by habc0807** [comment]
@jayZOU 
1、miniprogram_dev已删
2、dist中的冗余文件已删
3、ts 部分已去掉了，使用原生开发
