### ISSUE TITLE
wx boundingClientRect 获取定位不准确

### ISSUE THREAD

**Issue by jintangWang** [jayZOU/skeleton#6]
请问，这个你咋解决的？定位不准确，渲染的骨头模块位置大小都不太对

**Comment by jayZOU** [comment]
@jintangWang 没理解你说的定位不准确，给下示例代码？

**Comment by jintangWang** [comment]
就用的你的代码，但发现有些`class` 为  `skeleton-rect` 的元素获取到的位置和大小和实际的不太一致

**Comment by jayZOU** [comment]
![image](https://user-images.githubusercontent.com/8576977/60518740-b1d5db00-9d14-11e9-9293-699de4ae603d.png)

看下是不是这个
