### ISSUE TITLE
获取不到组件内的dom信息

### ISSUE THREAD

**Issue by Sallywa** [jayZOU/skeleton#8]
我用的是taro框架 把skeleton组件写到了page中 发现获取不到子组件的dom信息

**Comment by Sallywa** [comment]
看到您的更新了 完美解决了～ 不过还有一个新的问题就是如果我通过createSelectorQuery获取信息由于在执行的时候 后端还没有返回数据dom也未渲染 导致我拿不到dom节点信息（通常是个null）暂时的解决办法是用定时器延迟其执行，但是这也不是完美的解决办法，如果网络非常不好 仍然是绘制不出骨架屏的

**Comment by jayZOU** [comment]
骨架屏的渲染不应该依赖到后端给的数据，最好的做法是前端填入一些默认的数据去撑开DON节点来绘制骨架屏

**Comment by jayZOU** [comment]
提供一个思路，可以利用缓存来解决这个问题，初次访问用默认 data 数据来渲染骨架屏，异步去拉取真实数据、缓存，下次进入的话就可以直接用缓存数据来渲染
